language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install -g hexo

before_script:
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - ls -l
  - git init
  - git remote add origin https://github.com/Pandapm/pandapm.github.io.git
  - git config user.name "pandapm"
  - git config user.email "panda_m@126.com"
  - git add .
  - git status 
  - git commit -m "Update blogs"
  - git push --force "https://${GH_TOKEN}@${REF}" master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - REF: github.com/Pandapm/pandapm.github.io.git
